-- noinspection SqlDialectInspectionForFile

# FILE_METADATA AND TEMPORARY_FILE schemas

# --- !Ups

CREATE TABLE USER_PERMISSIONS (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MAX_FILES_COUNT INT NOT NULL,
    MAX_FILE_SIZE INT NOT NULL
);

INSERT INTO USER_PERMISSIONS VALUES(0, -1, -1);
INSERT INTO USER_PERMISSIONS VALUES(1, 10, 16);

CREATE TABLE USER (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LOGIN VARCHAR(64) NOT NULL,
    EMAIL VARCHAR(128) NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    FOREIGN KEY (PERMISSION_ID) REFERENCES USER_PERMISSIONS(ID) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE UNIQUE INDEX EMAIL_IDX ON USER(EMAIL);

# --- !Downs

DROP INDEX USER.EMAIL_IDX;
DROP TABLE USER;
DROP TABLE USER_PERMISSIONS;