-- noinspection SqlDialectInspectionForFile

# --- !Ups

CREATE TABLE SAMPLE_FILE (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  SAMPLE_NAME VARCHAR(64) NOT NULL,
  METADATA_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL,
  FOREIGN KEY (METADATA_ID) REFERENCES FILE_METADATA(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE USER ADD FOLDER_PATH VARCHAR(255) NOT NULL DEFAULT '<default>';

# --- !Downs

ALTER TABLE USER DROP COLUMN FOLDER;

DROP TABLE SAMPLE_FILE;