-- noinspection SqlDialectInspectionForFile

# --- !Ups

CREATE TABLE SAMPLE_FILE (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  METADATA_ID BIGINT NOT NULL,
  USER_ID BIGINT NOT NULL,
  FOREIGN KEY (METADATA_ID) REFERENCES FILE_METADATA(ID) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

# --- !Downs

DROP TABLE SAMPLE_FILE;