-- noinspection SqlDialectInspectionForFile

# --- !Ups

ALTER TABLE SAMPLE_FILE ADD READS_COUNT BIGINT NOT NULL DEFAULT -1;
ALTER TABLE SAMPLE_FILE ADD CLONOTYPES_COUNT BIGINT NOT NULL DEFAULT -1;

# --- !Downs

ALTER TABLE SAMPLE_FILE DROP COLUMN READS_COUNT;
ALTER TABLE SAMPLE_FILE DROP COLUMN CLONOTYPES_COUNT;