-- noinspection SqlDialectInspectionForFile

# --- !Ups

CREATE TABLE SAMPLE_TAG (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TAG_NAME VARCHAR(64) NOT NULL,
  TAG_COLOR VARCHAR(32) NOT NULL,
  USER_ID BIGINT NOT NULL
);

ALTER TABLE SAMPLE_FILE ADD TAG_ID BIGINT NOT NULL DEFAULT -1;

# --- !Downs

ALTER TABLE SAMPLE_FILE DROP COLUMN TAG_ID;

DROP TABLE SAMPLE_TAG;