-- noinspection SqlDialectInspectionForFile

# --- !Ups

CREATE TABLE SAMPLE_TAG (
  ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TAG_NAME VARCHAR(64) NOT NULL,
  TAG_COLOR VARCHAR(32) NOT NULL,
  USER_ID BIGINT NOT NULL
);

# --- !Downs

DROP TABLE SAMPLE_TAG;