-- noinspection SqlDialectInspectionForFile

# --- !Ups

INSERT INTO USER_PERMISSIONS VALUES(3, 3, 8, true, true, false);

ALTER TABLE USER ADD CREATE_IP VARCHAR(128) DEFAULT 'none' NOT NULL AFTER PERMISSION_ID;
ALTER TABLE USER ADD IS_TEMPORARY BOOLEAN DEFAULT FALSE NOT NULL AFTER CREATE_IP;
ALTER TABLE USER ADD CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL AFTER IS_TEMPORARY;
ALTER TABLE USER ADD LAST_ACCESSED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL AFTER CREATED_ON;

# --- !Downs

DELETE FROM USER_PERMISSIONS WHERE ID = 3;

ALTER TABLE USER DROP COLUMN LAST_ACCESSED_ON;
ALTER TABLE USER DROP COLUMN CREATED_ON;
ALTER TABLE USER DROP COLUMN IS_TEMPORARY;
ALTER TABLE USER DROP COLUMN CREATE_IP;
